apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGO_URL: "mongodb://mongo-0.mongo.dev,mongo-1.mongo.dev,mongo-2.mongo.dev,mongo-3.mongo.dev,mongo-4.mongo.dev:27017/?replicaSet=rs0"
