apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: dev
labels:
  - pairs:
      environment: dev
      managed-by: kustomize
patches:
  - path: configmap-patch.yaml
  - path: replicas-patch.yaml
