apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth-sa
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mongo 27017; do
                echo "Waiting for MongoDB..."
                sleep 2
              done
              echo "MongoDB is ready!"
      containers:
        - name: auth
          image: likhon22/kub_prac_auth:latest
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /auth
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /auth
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
