apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
subjects:
  - kind: ServiceAccount
    name: backend-sa
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-rolebinding
subjects:
  - kind: ServiceAccount
    name: auth-sa
roleRef:
  kind: Role
  name: auth-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-rolebinding
subjects:
  - kind: ServiceAccount
    name: frontend-sa
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io
